#!/bin/bash
IN=LVDS-1
OUT=VGA-1
OUTA=HDMI-1

if (xrandr | grep "$OUT connect" ); then 
#	echo $OUT
	xrandr --output $IN --auto --output $OUT --auto --right-of LVDS-1 --output $OUTA --off
	exit 0
elif (xrandr | grep "$OUTA connect"); then
	xrandr --output $IN --auto --output $OUTA --auto --right-of LVDS-1 --output $OUT --off
	exit 0
else
	xrandr --auto
fi

exit 0

